/**
 * get patients
 */

const rows = document.querySelectorAll('tr[mat-row]');

const patients = [
  {
    documentID: '0mgIDXL42VeVBfM07dgS',
    phone: '"07367951"',
    name: '"Emily "',
    patientEmail: '"emily@123.com"',
    physioEmail: '"claire@clinisport.com"',
    playlistId: '"af5f5803-c111-4d8a-801c-42e65b07c184"',
  },
  {
    documentID: '3jyrisM5SzjY656tX77G',
    phone: '"07773373"',
    name: '"Brendan Crossey "',
    patientEmail: '"brendan@hll.com"',
    physioEmail: '"claire@strokeful.com"',
    playlistId: '',
  },
  {
    documentID: '56kv64D2zaTN4KVwRwgZ',
    phone: '',
    name: '',
    patientEmail: '',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '',
  },
  {
    documentID: '5Inx9dUqMZW1p8fA8QFy',
    phone: '"1122131232"',
    name: '"Shoaib child arb"',
    patientEmail: '"shoaib.riaz+1@arbisoft.com"',
    physioEmail: '"shoaib.riaz@arbisoft.com"',
    playlistId: '',
  },
  {
    documentID: '5wPunVNUThlFYy9MDC67',
    phone: '"12322343234"',
    name: '"New Patient"',
    patientEmail: '"testpatientnew@gmail.com"',
    physioEmail: '"testdoctor@gmail.com"',
    playlistId: '"fc419f57-39d6-4c2a-bca8-b269826fb9e0"',
  },
  {
    documentID: '8VbEt3N4mg9dWMK4eFCX',
    phone: '"12345"',
    name: '"New test"',
    patientEmail: '"testing@gmil.in"',
    physioEmail: '"shoaib@ghx.com"',
    playlistId: '"df386a4c-b1f0-47a5-8707-d3a393d32979"',
  },
  {
    documentID: 'AmqlZPh1NXWKiTrnrwHH',
    phone: '"1231231234"',
    name: '"Test"',
    patientEmail: '"test@test.com"',
    physioEmail: '"onu3monu@gmail.com"',
    playlistId: '',
  },
  {
    documentID: 'CX2cKdTPuRZbgvB41iGa',
    phone: '',
    name: '',
    patientEmail: '',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '',
  },
  {
    documentID: 'EG3V6B5l5juwLKw6MPY4',
    phone: '"1234567890"',
    name: '"Stephen"',
    patientEmail: '"stephen@galviadigital.com"',
    physioEmail: '"stephen@galvidigital.com"',
    playlistId: '"4a897ffb-9562-4dfa-a7bb-ceda8e40c48d"',
  },
  {
    documentID: 'EWrHRyS9J0lqC7ksRHGz',
    phone: '',
    name: '"Rf"',
    patientEmail: '"dd@_&-.co.uk"',
    physioEmail: '"claire@clinisport.com"',
    playlistId: '',
  },
  {
    documentID: 'H7k3avwRq9DnU71d2U0O',
    phone: '"7523559391"',
    name: '"Sarah"',
    patientEmail: '"healthgainz@gmail.com"',
    physioEmail: '"clairemcmullan@live.com"',
    playlistId: '"b39d2f33-9cfb-4d74-baf1-532d078f11e8"',
  },
  {
    documentID: 'I9Pmmv4z9yUbBD7fwQc8',
    phone: '"12345678"',
    name: '"Stephen"',
    patientEmail: '"stephen@galviadigital.com"',
    physioEmail: '"test@mail.com"',
    playlistId: '"4a897ffb-9562-4dfa-a7bb-ceda8e40c48d"',
  },
  {
    documentID: 'JAeQDIm08DkbdVjZlSrU',
    phone: '"012909021"',
    name: '"Show Shoaib"',
    patientEmail: '"this.shoaib@gmail1.com"',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '"8a599614-9728-4a55-bf47-761e339ce60e"',
  },
  {
    documentID: 'JFQcgInGEwfAguVL9nYu',
    phone: '"+92 323 502 9955"',
    name: '"Shoaib Khazer"',
    patientEmail: '"this.shoaib+1@gmail.com"',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '"3db41dad-cfd6-4092-9bb4-c8a6c0a5f885"',
  },
  {
    documentID: 'LVQjXWGr9q9dyYgzlTB9',
    phone: '"123456789"',
    name: '"New Patient"',
    patientEmail: '"Some.new@gmail.com"',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '"71912b3a-0e3f-4391-b6a7-d18cac94d33f"',
  },
  {
    documentID: 'OE4JDKLXJX7Z6LJrkRA8',
    phone: '"21212"',
    name: '"New Patient 2"',
    patientEmail: '"This.sewq@gmail.com"',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '"71912b3a-0e3f-4391-b6a7-d18cac94d33f"',
  },
  {
    documentID: 'PKkdF1S0qVUmnIT0gRin',
    phone: '"123456767"',
    name: '"First Pat"',
    patientEmail: '"firt@xmail.com"',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '',
  },
  {
    documentID: 'QgJHrBCIAwDBmRlQcLim',
    phone: '"+1223132 2323"',
    name: '"Shareable new"',
    patientEmail: '"sharable@gmauil.don"',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '"8941afa2-3fd4-4b45-bc1a-2e5df24eaff5"',
  },
  {
    documentID: 'VD1uBKsOk8Nut9TbsGun',
    phone: '"1234567891"',
    name: '"Tester"',
    patientEmail: '"test@test.com"',
    physioEmail: '"mondalkamolesh34@gmail.com"',
    playlistId: '',
  },
  {
    documentID: 'XydXzTseAEamkzNohISG',
    phone: '"12345677"',
    name: '"Test Patient Updated"',
    patientEmail: '"test.patient@gmail.com"',
    physioEmail: '"testdoctor@gmail.com"',
    playlistId: '"bd710677-8388-4051-b6e1-dd59265ed4ab"',
  },
  {
    documentID: 'YO0NDfOSrRi0N53Zd5xQ',
    phone: '',
    name: '"Dr Holdsworth"',
    patientEmail: '',
    physioEmail: '"clairemcmullan@live.com"',
    playlistId: '',
  },
  {
    documentID: 'agHGAMNKVYkVJK7fYltT',
    phone: '',
    name: '"Claire"',
    patientEmail: '"claire@healthgainz.com"',
    physioEmail: '"claire@clinisport.com"',
    playlistId: '"af5f5803-c111-4d8a-801c-42e65b07c184"',
  },
  {
    documentID: 'dQzcUIa5MfoTchzfAaIk',
    phone: '"123456"',
    name: '"Anna Bill"',
    patientEmail: '"Anna.bill@gmail.com"',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '"a612804e-7fac-4065-ac99-5e5e86e84e98"',
  },
  {
    documentID: 'da6NYin3S6VT1kibs0w1',
    phone: '"07523"',
    name: '"Claire Mc"',
    patientEmail: '"clairemcmullan@live.com"',
    physioEmail: '"claire@clinisport.com"',
    playlistId: '"dfa8a839-0ba7-440c-ad24-9315c8a14491"',
  },
  {
    documentID: 'iijeTi0QO7jMYXHg02uK',
    phone: '"3232"',
    name: '"Ammar Sb"',
    patientEmail: '"1234"',
    physioEmail: '"This.shoaib@gmail.com"',
    playlistId: '',
  },
  {
    documentID: 'lICgl7DYTUcC5wnZzf6S',
    phone: '"1234567890"',
    name: '"Patient1"',
    patientEmail: '"patient1@mail.com"',
    physioEmail: '"stephen@galvidigital.com"',
    playlistId: '',
  },
  {
    documentID: 'lUqKGukc9vhkb8pCDEL1',
    phone: '',
    name: '"Sarah"',
    patientEmail: '',
    physioEmail: '"claire@strokeful.com"',
    playlistId: '',
  },
  {
    documentID: 'ozsoInlrIAkJWzonZiNH',
    phone: '',
    name: '"John Doe"',
    patientEmail: '"John.doe@gmail.com"',
    physioEmail: '"this.shoaib@gmail.com"',
    playlistId: '"f377bf85-ed12-43b1-a4b4-3799eacfa719"',
  },
  {
    documentID: 'pIri1dIQ6pqTJxZ0xiVV',
    phone: '',
    name: '"Stephen Ross"',
    patientEmail: '"stephen@galviadigital.com"',
    physioEmail: '"claire@clinisport.com"',
    playlistId: '"4a897ffb-9562-4dfa-a7bb-ceda8e40c48d"',
  },
  {
    documentID: 'sTqM5erZlVc08RAY6I9w',
    phone: '"123"',
    name: '"Fab"',
    patientEmail: '"f.campbellwest@gmail.com"',
    physioEmail: '"f.campbell.west@gmail.com"',
    playlistId: '',
  },
  {
    documentID: 'uvyqIxZ881KQZ938XD2T',
    phone: '"077235594562"',
    name: '"Sarah Wylie"',
    patientEmail: '"healthgainz@outlook.com"',
    physioEmail: '"claire@clinisport.com"',
    playlistId: '"2f7f8314-2915-4113-9bac-20a351bb3932"',
  },
  {
    documentID: 'wC4otrkDHb5Bx66oOryF',
    phone: '"0868377235"',
    name: '"Siobhan Brennan"',
    patientEmail: '"siobhanboneill@gmail.com"',
    physioEmail: '"siobhan@saleslab.ie"',
    playlistId: '"ff49aa2b-ca16-4d88-a63e-dc952d068930"',
  },
  {
    documentID: 'yb4LmTH90DmVTdYeUsgs',
    phone: '"7523559391"',
    name: '"Claire"',
    patientEmail: '"claire@healthgainz.com"',
    physioEmail: '"clairemcmullan@live.com"',
    playlistId: '',
  },
];

rows.forEach(row => {
  const cells = row.querySelectorAll('td');
  const rowData = {
    documentID: cells[0].textContent.trim(),
    phone: cells[1].textContent.trim(),
    name: cells[2].textContent.trim(),
    patientEmail: cells[3].textContent.trim(),
    physioEmail: cells[5].textContent.trim(),
    playlistId: cells[6].textContent.trim(),
  };
  data.push(rowData);
});
